disabled = false
languageCode = "en"
languageName = "English"
weight = 1
title = "kdayno"

[params]
displayName = "EN"
isoCode = "en"
rtl = false
dateFormat = "2 January 2006"
description = "Kevin Dayno Personal Website"
