[[main]]
none = "none"

[[main]]
name = "About"
pageRef = "about"
identifier = "6EXdkNdIHb"
weight = 1

[[main]]
name = "Notes"
pre = "link"
url = "www.notes.kdayno.com"
identifier = "0US2eYMNdO"
weight = 2

[[footer]]
none = "none"
